nelmio_cors:
  defaults:
    allow_origin:
      ["https://localhost:3000","http://localhost:3000", "https://moodly.cloud", "https://127.0.0.1"]
    allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: ["Link"]
    max_age: 3600
    allow_credentials: true
  paths:
    "^/api/":
      allow_origin:
        ["https://localhost:3000","http://localhost:3000", "https://moodly.cloud", "https://127.0.0.1"]
      allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
      allow_headers: ["Content-Type", "Authorization"]
      expose_headers: ["Link"]
      max_age: 3600
      allow_credentials: true
